### ISSUE TITLE
Waithing 14400 Sec = 4 Hours

### ISSUE THREAD

**Issue by chris1111** [qgustavor/megajs-cli#24]
For a big file of 5.77 GB
Now its the second part with the `--continue option`
Thank you for this anyway Good jog!
![Capture d’écran, le 2022-12-26 à 12 21 01](https://user-images.githubusercontent.com/6248794/209571279-be0a18ef-2376-47b5-b253-9b37af2c3e40.png)

Maybe a solution to avoid time ?

**Comment by qgustavor** [comment]
Do you have [a Pro account](https://mega.io/pro)? If so I can add a feature to download using the transfer quota from the account.

**Comment by chris1111** [comment]
No its a basic 50 G

**Comment by qgustavor** [comment]
Maybe it's still possible to use the quota from a basic account. I don't know, I never tried. What I often do is just wait the time and try again, most things I download I download weeks in advance so it works for me. I will try to implement a way to log in before downloading files in order to use the account quota.

**Comment by chris1111** [comment]
Its done now 😀

![Capture d’écran, le 2022-12-26 à 12 32 57](https://user-images.githubusercontent.com/6248794/209571978-410f8db8-96cc-4126-8834-0584032a4f48.png)

**Comment by qgustavor** [comment]
I checked the code, this tool is still using callbacks, I prefer rewriting it to use Deno rather than edit the current code, I think it would take less effort. Maybe later, for now I will close this issue.

**Comment by chris1111** [comment]
This is a known issue with mega more the 5 giga downloding big file
If you fix this a lot of user will be verry happy Thank you verry much

**Comment by qgustavor** [comment]
By the way, regarding a rewrite, I will keep using Node: I just noticed Deno will be more of a trouble than an help.
